#!/usr/bin/env bash

pkill sxhkd > /dev/null
sxhkd -m 1&

# alow to move floating windows with mouse
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# setup monitors
monitors=($(bspc query -M --names | tr ' ' '\n' | sort --reverse))
max_desktops=7

bspc monitor "${monitors[0]}" -d $(seq -s ' ' 1 1 ${max_desktops})
if [ "${#monitors[@]}" -eq 2 ]; then
    bspc monitor "${monitors[1]}" -d $(seq -s ' ' 1 1 ${max_desktops})
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefoxdeveloperedition state=floating desktop='^2'
bspc rule -a 'VirtualBox Manager' desktop='^6'
bspc rule -a 'Vmware' desktop='^6'

$HOME/.config/bspwm/autostart.sh
# wait for the network interface to be up
sleep 1
$HOME/.config/polybar/launch.sh
