#!/usr/bin/env bash

pkill sxhkd > /dev/null
sxhkd -m 1&

# setup monitors
monitors=($(bspc query -M --names | tr ' ' '\n' | sort --reverse))
max_desktops=6

if [ "${#monitors[@]}" -eq 1 ]; then
    bspc monitor "${monitors[0]}" -d $(seq -s ' ' 0 1 ${max_desktops})
else
    bspc monitor "${monitors[0]}" -d $(seq -s ' ' 0 1 ${max_desktops})
    bspc monitor "${monitors[1]}" -d $(seq -s ' ' 0 1 ${max_desktops}) 0
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/autostart.sh
