# Inserts a blank line between shell prompts
add_newline = true

# Which is equivalent to
format = """
$username\
$hostname\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$shell\
$line_break\
$character"""

right_format="""
$docker_context\
$package\
$cmake\
$deno\
$golang\
$java\
$kotlin\
$nodejs\
$perl\
$php\
$python\
$nix_shell\
$ruby\
$rust\
$vagrant\
$memory_usage\
$env_var\
$custom\
$cmd_duration\
$lua\
$jobs\
$time\
$status\
"""

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
vicmd_symbol = "[❮](bold green) "


[nix_shell]
disabled = true
impure_msg = "[impure shell](bold red)"
pure_msg = "[pure shell](bold green)"
format = 'via [☃️ $state( \($name\))](bold blue) '

[directory]
truncate_to_repo = false

[git_status]
conflicted = "="
ahead = "⇡${count}"
behind = "${count}⇣"
diverged = "${count}⇕"
untracked = "${count}?"
stashed = "${count}$"
modified = "${count}!"
staged = "${count}+"
renamed = "${count}»"
deleted = "${count}✘"

[rust]
format = "via [$symbol ($version )]($style)"
symbol = ""
