-- keybindings
vim.api.nvim_set_keymap('n', '<leader>f', '[fzf-p]', {})
vim.api.nvim_set_keymap('x', '<leader>f', '[fzf-p]', {})

vim.api.nvim_set_keymap('n', '[fzf-p]p', ':<C-u>CocCommand fzf-preview.FromResources project_mru git<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]gs', ':<C-u>CocCommand fzf-preview.GitStatus<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]ga', ':<C-u>CocCommand fzf-preview.GitActions<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]b', ':<C-u>CocCommand fzf-preview.Buffers<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]B', ':<C-u>CocCommand fzf-preview.AllBuffers<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]o', ':<C-u>CocCommand fzf-preview.FromResources buffer project_mru<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]<C-o>', ':<C-u>CocCommand fzf-preview.Jumps<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]g;', ':<C-u>CocCommand fzf-preview.Changes<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]/', ':<C-u>CocCommand fzf-preview.Lines --add-fzf-arg=--no-sort --add-fzf-arg=--query="\'"<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]*', ':<C-u>CocCommand fzf-preview.Lines --add-fzf-arg=--no-sort --add-fzf-arg=--query="\'<C-r>=expand(\'<cword>\')<CR>"<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]gr', ':<C-u>CocCommand fzf-preview.ProjectGrep<Space>', {noremap = true})
vim.api.nvim_set_keymap('x', '[fzf-p]gr', 'sy:CocCommand   fzf-preview.ProjectGrep<Space>-F<Space>"<C-r>=substitute(substitute(@s, \'\n\', \'\', \'g\'), \'/\', \'\\/\', \'g\')<CR>"', {noremap = true})
vim.api.nvim_set_keymap('n', '[fzf-p]t', ':<C-u>CocCommand fzf-preview.BufferTags<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]q', ':<C-u>CocCommand fzf-preview.QuickFix<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '[fzf-p]l', ':<C-u>CocCommand fzf-preview.LocationList<CR>', {noremap = true, silent = true})
